- hosts: localhost
  gather_facts: false
  environment:
    OS_CLOUD: devstack

  tasks:
    - name: list baremetal nodes
      command: >-
        openstack baremetal node list -f json
      register: result
    
    - debug:
        var: result.stdout

    - name: list hosted zones
      amazon.aws.route53_info:
        query: hosted_zone
      register: hosted_zones

    - debug:
        var: hosted_zones
